from enum import Enum


class EngineStatus(Enum):
    ENGINE_STATUS_RUNNING = 1
    ENGINE_STATUS_STOPPING = 2
    ENGINE_STATUS_STOPPED = 3
    ENGINE_STATUS_SUSPENDING = 4


class SpiderStatus(Enum):
    SPIDER_STATUS_RUNNING = 1
    SPIDER_STATUS_STOPPED = 2
    SPIDER_STATUS_DELETED = 3
